stages:
    - php70
    - php56
    - php55

php7.0:
    except:
        - tags
    image: unitedasian/php:7.0
    script:
        - composer update -n --no-plugins --no-progress --no-scripts --no-suggest
    stage: php70
    tags:
        - php70

php5.6:
    image: unitedasian/php:5.6
    only:
        - master
    script:
        - composer update -n --no-plugins --no-progress --no-scripts --no-suggest
    stage: php56
    tags:
        - php56

php5.5:
    image: unitedasian/php:5.5
    only:
        - master
    script:
        - composer update -n --no-plugins --no-progress --no-scripts --no-suggest
    stage: php55
    tags:
        - php55
